//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int StoreID { get; set; }
        public int SKU { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public System.DateTime Date { get; set; }
    }
}
